title: "Footer"
description: |
  A place where footers (specifically their styles) come to die.

patterns:
  basic-footer:
    title: "Basic Footer"
    description: |
      Links within links which lead to pages of links.
