permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Milk & Honey"
  description: |
    Milk & Honey offer natural solutions for life's hardest problems.
  font_url: "https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400i,700&display=swap"
  colors:
    background: "--color-another-blue"
    accent: "--gradient-gold"
    patterns:
      brand.logos: "--color-secondary-light"
  rationales:
    typefaces.secondary: |
      PT Sans Narrow is only to be used for highlight text: headings, buttons, banners, etc.
    color.primary: |
      The Primary colours represent herbivores & plants & greenery. They should be used for text and in foregrounds.
    colors.secondary: |
      The secondary colours are more neutral, continuing with the earth tones, and should be used for backgrounds.
  collections:
    products:
      output: true
  default:
    - scope:
        path: _products
      values:
        layout: product

  layouts:
      default: |
        The default layout has my site standard header and footer.
      product: |
        The product layout has my products page layouts.
